name: on-pull-request

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/**'

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.7

      - name: Check code-style
        run: terraform fmt -recursive -check

  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.GH_ORGANIZATION_TFSTATE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_ORGANIZATION_TFSTATE_AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.7

      - name: Terraform Init (Check Lockfile)
        run: terraform init -lockfile=readonly

      - name: Terraform validate
        run: terraform validate -no-color

  plan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: terraform
    needs:
      - check-code-style
      - validate
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.GH_ORGANIZATION_TFSTATE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_ORGANIZATION_TFSTATE_AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.MINERVA_SAMA_APP_ID }}
          private-key: ${{ secrets.MINERVA_SAMA_APP_PRIVATE_KEY }}
          owner: bright-room

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.7

      - name: Terraform Init
        run: terraform init -lockfile=readonly

      - name: Terraform plan
        id: plan
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: terraform plan -no-color

      - name: Plan result
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PLAN_OUTPUT: ${{ steps.plan.outputs.stdout }}
        run: |
          cat <<EOF > /tmp/comment.md
          <details>
          <summary>Terraform Plan</summary>

          \`\`\`
          ${PLAN_OUTPUT}
          \`\`\`

          </details>
          EOF
          gh pr comment ${{ github.event.number }} --body-file /tmp/comment.md
